name: Challenge Three

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Run the script
        run: python hello.py
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
      - name: Create an artifact
        uses: actions/upload-artifact@v2
        with:
          name: hello
          path: .
